package com.payflow.util;

import java.security.SecureRandom;
import java.time.Instant;

/**
 * Utility for generating opaque, collision-resistant <em>business</em> identifiers
 * (Rule 8: dedicated ID utility class).
 *
 * <p>Database surrogate primary keys are generated by Hibernate ({@code @GeneratedValue}).
 * This class generates the externally visible reference identifiers (e.g. transaction
 * reference numbers, public user references) that are safe to expose over the API and never
 * leak the underlying auto-increment sequence.</p>
 *
 * <p>The format is a 26-character, lexicographically sortable ULID (Crockford Base32) built
 * from a 48-bit timestamp and 80 bits of secure randomness, optionally prefixed for human
 * readability (e.g. {@code TXN_01HZ...}).</p>
 *
 * <p>The class is final with a private constructor: it is a stateless utility and must not be
 * instantiated or subclassed.</p>
 */
public final class IdentifierGenerator {

    /** Crockford Base32 alphabet (excludes I, L, O, U to avoid ambiguity). */
    private static final char[] ENCODING = "0123456789ABCDEFGHJKMNPQRSTVWXYZ".toCharArray();
    private static final int TIME_LENGTH = 10;
    private static final int RANDOM_LENGTH = 16;
    private static final int ULID_LENGTH = TIME_LENGTH + RANDOM_LENGTH;
    private static final SecureRandom RANDOM = new SecureRandom();

    private IdentifierGenerator() {
        throw new AssertionError("IdentifierGenerator is a utility class and must not be instantiated");
    }

    /**
     * Generates a raw 26-character ULID.
     *
     * @return a lexicographically sortable, time-ordered unique identifier
     */
    public static String newUlid() {
        char[] buffer = new char[ULID_LENGTH];
        encodeTime(Instant.now().toEpochMilli(), buffer);
        encodeRandom(buffer);
        return new String(buffer);
    }

    /**
     * Generates a prefixed business reference, e.g. {@code newReference("TXN")}
     * yields {@code TXN_01HZX3...}.
     *
     * @param prefix short domain prefix (must not be blank)
     * @return the prefixed reference
     * @throws IllegalArgumentException if {@code prefix} is null or blank
     */
    public static String newReference(String prefix) {
        if (prefix == null || prefix.isBlank()) {
            throw new IllegalArgumentException("prefix must not be blank");
        }
        return prefix + "_" + newUlid();
    }

    private static void encodeTime(long time, char[] buffer) {
        for (int i = TIME_LENGTH - 1; i >= 0; i--) {
            buffer[i] = ENCODING[(int) (time & 0x1f)];
            time >>>= 5;
        }
    }

    private static void encodeRandom(char[] buffer) {
        for (int i = TIME_LENGTH; i < ULID_LENGTH; i++) {
            buffer[i] = ENCODING[RANDOM.nextInt(ENCODING.length)];
        }
    }
}
