package com.payflow.entity;

import jakarta.persistence.Column;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.Version;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.io.Serializable;
import java.time.Instant;

/**
 * Abstract base for all persistent entities (OOP: inheritance + reuse, Rule 12).
 *
 * <p>Centralises the surrogate primary key, JPA auditing timestamps, and the optimistic
 * locking {@code version} column so concrete entities stay focused on domain fields
 * (Separation of Concerns).</p>
 *
 * <p>The {@link Version} field provides database-level optimistic concurrency control; it is
 * complemented at the application layer by fine-grained striped locking in the service tier
 * (mentor feedback 22.a).</p>
 */
@Getter
@Setter
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity implements Serializable {

    /** Surrogate primary key generated by Hibernate (MySQL AUTO_INCREMENT). */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** Optimistic-lock guard incremented by Hibernate on every update. */
    @Version
    @Column(name = "version", nullable = false)
    private Long version;
}
