package com.payflow.entity;

import com.payflow.enums.Currency;
import com.payflow.enums.TransactionStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

/**
 * An immutable record of a single money transfer.
 *
 * <p>Per the assignment scope, sender and receiver are stored as plain UPI-ID strings rather
 * than foreign keys to {@link User}. Columns are indexed on {@code sender_upi_id} and
 * {@code receiver_upi_id} so paginated transaction-history queries are index-backed
 * (mentor feedback 22.f).</p>
 */
@Entity
@Table(
        name = "transactions",
        indexes = {
                @Index(name = "uk_transactions_reference_id", columnList = "reference_id", unique = true),
                @Index(name = "idx_transactions_sender", columnList = "sender_upi_id"),
                @Index(name = "idx_transactions_receiver", columnList = "receiver_upi_id")
        }
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Transaction extends BaseEntity {

    /** Opaque external reference (e.g. {@code TXN_01HZ...}) generated by the ID utility. */
    @Column(name = "reference_id", nullable = false, updatable = false, length = 40)
    private String referenceId;

    @Column(name = "sender_upi_id", nullable = false, length = 80)
    private String senderUpiId;

    @Column(name = "receiver_upi_id", nullable = false, length = 80)
    private String receiverUpiId;

    @Column(name = "amount", nullable = false, precision = 19, scale = 2)
    private BigDecimal amount;

    @Enumerated(EnumType.STRING)
    @Column(name = "currency", nullable = false, length = 3)
    private Currency currency;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private TransactionStatus status;

    @Column(name = "note", length = 255)
    private String note;

    /** Set when {@code status == FAILED} to explain why the transfer did not settle. */
    @Column(name = "failure_reason", length = 255)
    private String failureReason;
}
