package com.payflow.entity;

import com.payflow.enums.Currency;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Enumerated;
import jakarta.persistence.EnumType;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

/**
 * A PayFlow wallet owner.
 *
 * <p>Demonstrates the JPA naming convention: camelCase Java fields ({@code upiId},
 * {@code phoneNumber}) map to snake_case columns ({@code upi_id}, {@code phone_number}).</p>
 *
 * <p>Monetary {@code balance} uses {@link BigDecimal} (not {@code double}) for exact decimal
 * arithmetic &mdash; the correct production choice for money. The {@code upi_id} column is
 * uniquely indexed to enforce the business rule that UPI IDs are unique and to make the
 * {@code findByUpiId} lookup an index seek (mentor feedback 22.f: query optimization).</p>
 */
@Entity
@Table(
        name = "users",
        indexes = {
                @Index(name = "uk_users_upi_id", columnList = "upi_id", unique = true),
                @Index(name = "uk_users_reference_id", columnList = "reference_id", unique = true)
        }
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User extends BaseEntity {

    /** Opaque external reference (e.g. {@code USR_01HZ...}) generated by the ID utility. */
    @Column(name = "reference_id", nullable = false, updatable = false, length = 40)
    private String referenceId;

    @Column(name = "name", nullable = false, length = 120)
    private String name;

    @Column(name = "upi_id", nullable = false, length = 80)
    private String upiId;

    @Column(name = "phone_number", nullable = false, length = 15)
    private String phoneNumber;

    @Column(name = "balance", nullable = false, precision = 19, scale = 2)
    private BigDecimal balance;

    @Enumerated(EnumType.STRING)
    @Column(name = "currency", nullable = false, length = 3)
    private Currency currency;
}
